batch_size: 16
categories:
- structured
- disordered
data_path: data/dataset/DisProt_PDB/
datasets_to_test:
- dev
debug: false
emb_size:
  ESM2: 1280
  ESM2_150m: 640
  ESM2_35m: 480
  ESM2_650m: 1280
  ESM2_8m: 320
  ProstT5: 1024
  ProtT5: 1024
  esmc_300m: 960
  esmc_600m: 1152
filters: 200
kernel_size: 11
loss_class_weights:
- 1.0
- 1.0
lr: 2.0099723934551552e-05
n_resnet: 1
negative_label_scaling: null
nepoch: 500
pLM: ProstT5
p_dropout: 0.0
patience: 10
repeats: 9
soft_max: true
subset: null
win_len: 35
